name: Discord bot hosting

on:
  push:
    branches:
      - main

jobs:
  host:
    name: Host Spoyt on Discord
    runs-on: self-hosted
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        .\venv\Scripts\activate

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run the app
      run: |
        python -Om Spoyt
